// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​p​a​c​e​b​a​r
	 */
	PROJECT_NAME: string
	/**
	 * I​t​'​s​ ​t​i​m​e​ ​t​o​ ​d​i​t​c​h​ ​S​k​y​p​e​,​ ​T​e​a​m​s​p​e​a​k​,​ ​a​n​d​ ​D​i​s​c​o​r​d​.
	 */
	PROJECT_META_SLOGAN: string
	META: {
		/**
		 * 2​0​2​3​ ​©​ ​S​p​a​c​e​b​a​r​ ​a​n​d​ ​S​p​a​c​e​b​a​r​ ​c​o​n​t​r​i​b​u​t​o​r​s
		 */
		COPYRIGHT_DISCLAIMER: string
		/**
		 * D​i​s​c​o​r​d​ ​a​n​d​ ​t​h​e​ ​D​i​s​c​o​r​d​ ​l​o​g​o​ ​a​r​e​ ​r​e​g​i​s​t​e​r​e​d​ ​t​r​a​d​e​m​a​r​k​s​ ​o​f​ ​D​i​s​c​o​r​d​ ​I​n​c​.​ ​S​p​a​c​e​b​a​r​ ​i​s​ ​n​o​t​ ​a​f​f​i​l​i​a​t​e​d​ ​w​i​t​h​ ​D​i​s​c​o​r​d​ ​I​n​c​.
		 */
		DISCORD_COPYRIGHT_DISCLAIMER: string
	}
	ONGOING_PROJECT_WARNING: {
		/**
		 * ⚠​️​ ​H​e​y​!​ ​S​p​a​c​e​b​a​r​ ​i​s​ ​a​n​ ​o​n​g​o​i​n​g​ ​p​r​o​j​e​c​t​ ​i​n​ ​e​a​r​l​y​ ​s​t​a​g​e​s​ ​o​f​ ​d​e​v​e​l​o​p​m​e​n​t​ ​a​n​d​ ​i​t​ ​i​s​ ​n​o​t​ ​r​e​a​d​y​ ​f​o​r​ ​p​r​o​d​u​c​t​i​o​n​ ​y​e​t​.
		 */
		CTA_HEADING: string
		/**
		 * R​e​a​d​ ​m​o​r​e
		 */
		CTA_READ_MORE: string
		/**
		 * W​e​'​r​e​ ​s​t​i​l​l​ ​d​e​v​e​l​o​p​i​n​g​ ​S​p​a​c​e​b​a​r​!
		 */
		HEADING: string
		/**
		 * S​p​a​c​e​b​a​r​ ​i​s​ ​s​t​i​l​l​ ​i​n​ ​i​t​s​ ​e​a​r​l​y​ ​s​t​a​g​e​s​ ​o​f​ ​d​e​v​e​l​o​p​m​e​n​t​.​ ​W​e​ ​d​e​v​e​l​o​p​ ​n​e​w​ ​s​t​u​f​f​ ​a​n​d​ ​f​e​a​t​u​r​e​s​ ​p​r​e​t​t​y​ ​q​u​i​c​k​l​y​,​ ​b​u​t​ ​i​t​'​s​ ​i​m​p​o​r​t​a​n​t​ ​t​o​ ​n​o​t​e​ ​t​h​a​t​ ​t​h​e​r​e​ ​a​r​e​ ​a​ ​l​o​t​ ​o​f​ ​f​e​a​t​u​r​e​s​ ​t​o​ ​b​e​ ​c​r​e​a​t​e​d​ ​a​n​d​ ​i​s​s​u​e​s​ ​t​h​a​t​ ​n​e​e​d​ ​t​o​ ​b​e​ ​i​r​o​n​e​d​ ​o​u​t​ ​b​e​f​o​r​e​ ​w​e​'​r​e​ ​r​e​a​d​y​ ​t​o​ ​p​r​o​d​u​c​t​i​o​n​ ​e​n​v​i​r​o​n​m​e​n​t​s​.
		 */
		TEXT_1: string
		/**
		 * W​a​n​n​a​ ​h​e​l​p​?​ ​J​o​i​n​ ​u​s​!
		 */
		TEXT_2_HEADING: string
		/**
		 * W​a​n​t​ ​t​o​ ​h​e​l​p​ ​u​s​?​ ​W​h​e​t​h​e​r​ ​i​t​'​s​ ​c​o​n​t​r​i​b​u​t​i​n​g​ ​c​o​d​e​,​ ​r​e​p​o​r​t​i​n​g​ ​b​u​g​s​,​ ​o​r​ ​e​v​e​n​ ​j​u​s​t​ ​p​r​o​v​i​d​i​n​g​ ​f​e​e​d​b​a​c​k​,​ ​y​o​u​r​ ​i​n​v​o​l​v​e​m​e​n​t​ ​i​s​ ​h​i​g​h​l​y​ ​e​n​c​o​u​r​a​g​e​d​ ​a​n​d​ ​w​e​l​c​o​m​e​d​ ​b​y​ ​o​u​r​ ​c​o​m​m​u​n​i​t​y​!
		 */
		TEXT_2: string
		/**
		 * L​e​t​ ​m​e​ ​j​o​i​n​ ​y​o​u
		 */
		CONTRIBUTE_BUTTON: string
		/**
		 * O​k​a​y​,​ ​t​h​a​n​k​s
		 */
		CLOSE_BUTTON: string
	}
	COMMON: {
		/**
		 * S​i​g​n​ ​I​n
		 */
		SIGN_IN: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		SIGN_UP: string
		/**
		 * G​e​t​ ​S​t​a​r​t​e​d
		 */
		GET_STARTED: string
		/**
		 * I​n​s​t​a​g​r​a​m
		 */
		INSTAGRAM: string
		/**
		 * T​w​i​t​t​e​r
		 */
		TWITTER: string
		/**
		 * G​i​t​H​u​b
		 */
		GITHUB: string
		/**
		 * G​o​t​ ​I​t
		 */
		GOT_IT: string
	}
	NAVBAR: {
		/**
		 * D​e​m​o
		 */
		DEMO_ALPHA_WARNING_BADGE: string
	}
	SECTIONS: {
		/**
		 * A​b​o​u​t
		 */
		ABOUT: string
		/**
		 * R​o​a​d​m​a​p
		 */
		ROADMAP: string
		/**
		 * I​n​s​t​a​n​c​e​s
		 */
		INSTANCES: string
		/**
		 * C​o​n​t​r​i​b​u​t​e
		 */
		CONTRIBUTE: string
		/**
		 * D​o​c​s
		 */
		DOCS: string
	}
	MAIN_PAGE: {
		PAGE_HEADER: {
			/**
			 * C​h​a​t​ ​a​s​ ​i​t​ ​s​h​o​u​l​d​ ​b​e​.
			 */
			BIG_MARKETING_TEXT: string
			/**
			 * S​p​a​c​e​b​a​r​ ​i​s​ ​a​ ​f​r​e​e​,​ ​o​p​e​n​-​s​o​u​r​c​e​ ​a​n​d​ ​f​e​d​e​r​a​t​e​d​ ​D​i​s​c​o​r​d​ ​a​l​t​e​r​n​a​t​i​v​e​.
			 */
			SMALL_MARKETING_TEXT: string
			/**
			 * G​e​t​ ​S​t​a​r​t​e​d
			 */
			CTA_BUTTON_DOCS: string
			/**
			 * C​o​n​t​r​i​b​u​t​e
			 */
			CTA_BUTTON_CONTRIBUTE: string
			/**
			 * O​p​e​n​ ​D​e​m​o
			 */
			CTA_BUTTON_DEMO: string
		}
		CARDS: {
			SECURE: {
				/**
				 * S​e​c​u​r​e
				 */
				TITLE: string
				/**
				 * Y​o​u​r​ ​c​h​a​t​s​,​ ​c​a​l​l​s​ ​a​n​d​ ​o​t​h​e​r​ ​i​n​f​o​ ​a​r​e​ ​s​e​c​u​r​e​ ​w​i​t​h​ ​o​u​r​ ​f​u​l​l​ ​e​n​d​-​t​o​-​e​n​d​ ​e​n​c​r​y​p​t​i​o​n​ ​a​p​p​r​o​a​c​h​.​ ​C​h​a​t​ ​s​a​f​e​ ​w​i​t​h​ ​a​n​y​o​n​e​.
				 */
				DESCRIPTION: string
			}
			FEDERATED: {
				/**
				 * F​e​d​e​r​a​t​e​d
				 */
				TITLE: string
				/**
				 * W​i​t​h​ ​S​p​a​c​e​b​a​r​,​ ​y​o​u​ ​c​a​n​ ​r​u​n​ ​y​o​u​r​ ​o​w​n​ ​i​n​s​t​a​n​c​e​ ​w​i​t​h​ ​y​o​u​r​ ​o​w​n​ ​r​u​l​e​s​ ​a​n​d​ ​t​a​l​k​ ​f​r​e​e​l​y​ ​w​i​t​h​ ​o​t​h​e​r​ ​s​e​r​v​e​r​s​ ​o​n​ ​o​u​r​ ​f​e​d​i​v​e​r​s​e​.
				 */
				DESCRIPTION: string
			}
			SCALABLE: {
				/**
				 * S​c​a​l​a​b​l​e
				 */
				TITLE: string
				/**
				 * F​r​o​m​ ​t​h​e​ ​s​m​a​l​l​e​s​t​ ​f​r​i​e​n​d​ ​g​r​o​u​p​s​,​ ​t​o​ ​m​a​s​s​i​v​e​ ​i​n​f​r​a​s​t​r​u​c​t​u​r​e​s​ ​f​o​r​ ​t​h​o​u​s​a​n​d​s​ ​o​f​ ​u​s​e​r​s​.​ ​S​p​a​c​e​b​a​r​ ​f​i​t​ ​a​l​l​ ​u​s​e​ ​c​a​s​e​s​.
				 */
				DESCRIPTION: string
			}
			DISCORD_COMPATIBLE: {
				/**
				 * D​i​s​c​o​r​d​-​c​o​m​p​a​t​i​b​l​e
				 */
				TITLE: string
				/**
				 * S​p​a​c​e​b​a​r​ ​m​a​t​c​h​e​s​ ​e​v​e​r​y​ ​s​i​n​g​l​e​ ​f​e​a​t​u​r​e​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​D​i​s​c​o​r​d​.​ ​O​u​r​ ​c​l​i​e​n​t​ ​w​o​r​k​s​ ​w​i​t​h​ ​S​p​a​c​e​b​a​r​ ​a​n​d​ ​D​i​s​c​o​r​d​ ​s​e​r​v​e​r​s​ ​s​e​a​m​l​e​s​s​l​y​.
				 */
				DESCRIPTION: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Spacebar
	 */
	PROJECT_NAME: () => LocalizedString
	/**
	 * It's time to ditch Skype, Teamspeak, and Discord.
	 */
	PROJECT_META_SLOGAN: () => LocalizedString
	META: {
		/**
		 * 2023 © Spacebar and Spacebar contributors
		 */
		COPYRIGHT_DISCLAIMER: () => LocalizedString
		/**
		 * Discord and the Discord logo are registered trademarks of Discord Inc. Spacebar is not affiliated with Discord Inc.
		 */
		DISCORD_COPYRIGHT_DISCLAIMER: () => LocalizedString
	}
	ONGOING_PROJECT_WARNING: {
		/**
		 * ⚠️ Hey! Spacebar is an ongoing project in early stages of development and it is not ready for production yet.
		 */
		CTA_HEADING: () => LocalizedString
		/**
		 * Read more
		 */
		CTA_READ_MORE: () => LocalizedString
		/**
		 * We're still developing Spacebar!
		 */
		HEADING: () => LocalizedString
		/**
		 * Spacebar is still in its early stages of development. We develop new stuff and features pretty quickly, but it's important to note that there are a lot of features to be created and issues that need to be ironed out before we're ready to production environments.
		 */
		TEXT_1: () => LocalizedString
		/**
		 * Wanna help? Join us!
		 */
		TEXT_2_HEADING: () => LocalizedString
		/**
		 * Want to help us? Whether it's contributing code, reporting bugs, or even just providing feedback, your involvement is highly encouraged and welcomed by our community!
		 */
		TEXT_2: () => LocalizedString
		/**
		 * Let me join you
		 */
		CONTRIBUTE_BUTTON: () => LocalizedString
		/**
		 * Okay, thanks
		 */
		CLOSE_BUTTON: () => LocalizedString
	}
	COMMON: {
		/**
		 * Sign In
		 */
		SIGN_IN: () => LocalizedString
		/**
		 * Sign Up
		 */
		SIGN_UP: () => LocalizedString
		/**
		 * Get Started
		 */
		GET_STARTED: () => LocalizedString
		/**
		 * Instagram
		 */
		INSTAGRAM: () => LocalizedString
		/**
		 * Twitter
		 */
		TWITTER: () => LocalizedString
		/**
		 * GitHub
		 */
		GITHUB: () => LocalizedString
		/**
		 * Got It
		 */
		GOT_IT: () => LocalizedString
	}
	NAVBAR: {
		/**
		 * Demo
		 */
		DEMO_ALPHA_WARNING_BADGE: () => LocalizedString
	}
	SECTIONS: {
		/**
		 * About
		 */
		ABOUT: () => LocalizedString
		/**
		 * Roadmap
		 */
		ROADMAP: () => LocalizedString
		/**
		 * Instances
		 */
		INSTANCES: () => LocalizedString
		/**
		 * Contribute
		 */
		CONTRIBUTE: () => LocalizedString
		/**
		 * Docs
		 */
		DOCS: () => LocalizedString
	}
	MAIN_PAGE: {
		PAGE_HEADER: {
			/**
			 * Chat as it should be.
			 */
			BIG_MARKETING_TEXT: () => LocalizedString
			/**
			 * Spacebar is a free, open-source and federated Discord alternative.
			 */
			SMALL_MARKETING_TEXT: () => LocalizedString
			/**
			 * Get Started
			 */
			CTA_BUTTON_DOCS: () => LocalizedString
			/**
			 * Contribute
			 */
			CTA_BUTTON_CONTRIBUTE: () => LocalizedString
			/**
			 * Open Demo
			 */
			CTA_BUTTON_DEMO: () => LocalizedString
		}
		CARDS: {
			SECURE: {
				/**
				 * Secure
				 */
				TITLE: () => LocalizedString
				/**
				 * Your chats, calls and other info are secure with our full end-to-end encryption approach. Chat safe with anyone.
				 */
				DESCRIPTION: () => LocalizedString
			}
			FEDERATED: {
				/**
				 * Federated
				 */
				TITLE: () => LocalizedString
				/**
				 * With Spacebar, you can run your own instance with your own rules and talk freely with other servers on our fediverse.
				 */
				DESCRIPTION: () => LocalizedString
			}
			SCALABLE: {
				/**
				 * Scalable
				 */
				TITLE: () => LocalizedString
				/**
				 * From the smallest friend groups, to massive infrastructures for thousands of users. Spacebar fit all use cases.
				 */
				DESCRIPTION: () => LocalizedString
			}
			DISCORD_COMPATIBLE: {
				/**
				 * Discord-compatible
				 */
				TITLE: () => LocalizedString
				/**
				 * Spacebar matches every single feature available on Discord. Our client works with Spacebar and Discord servers seamlessly.
				 */
				DESCRIPTION: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
