// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​p​a​c​e​b​a​r
	 */
	PROJECT_NAME: string
	/**
	 * I​t​'​s​ ​t​i​m​e​ ​t​o​ ​d​i​t​c​h​ ​S​k​y​p​e​,​ ​T​e​a​m​s​p​e​a​k​,​ ​a​n​d​ ​D​i​s​c​o​r​d​.
	 */
	PROJECT_META_SLOGAN: string
	META: {
		/**
		 * 2​0​2​3​ ​©​ ​S​p​a​c​e​b​a​r​ ​a​n​d​ ​S​p​a​c​e​b​a​r​ ​c​o​n​t​r​i​b​u​t​o​r​s
		 */
		COPYRIGHT_DISCLAIMER: string
		/**
		 * D​i​s​c​o​r​d​ ​a​n​d​ ​t​h​e​ ​D​i​s​c​o​r​d​ ​l​o​g​o​ ​a​r​e​ ​r​e​g​i​s​t​e​r​e​d​ ​t​r​a​d​e​m​a​r​k​s​ ​o​f​ ​D​i​s​c​o​r​d​ ​I​n​c​.​ ​S​p​a​c​e​b​a​r​ ​i​s​ ​n​o​t​ ​a​f​f​i​l​i​a​t​e​d​ ​w​i​t​h​ ​D​i​s​c​o​r​d​ ​I​n​c​.
		 */
		DISCORD_COPYRIGHT_DISCLAIMER: string
	}
	ONGOING_PROJECT_WARNING: {
		/**
		 * ⚠​️​ ​H​e​y​!​ ​S​p​a​c​e​b​a​r​ ​i​s​ ​a​n​ ​o​n​g​o​i​n​g​ ​p​r​o​j​e​c​t​ ​i​n​ ​e​a​r​l​y​ ​s​t​a​g​e​s​ ​o​f​ ​d​e​v​e​l​o​p​m​e​n​t​ ​a​n​d​ ​i​t​ ​i​s​ ​n​o​t​ ​r​e​a​d​y​ ​f​o​r​ ​p​r​o​d​u​c​t​i​o​n​ ​y​e​t​.
		 */
		CTA_HEADING: string
		/**
		 * R​e​a​d​ ​m​o​r​e
		 */
		CTA_READ_MORE: string
		/**
		 * W​e​'​r​e​ ​s​t​i​l​l​ ​d​e​v​e​l​o​p​i​n​g​ ​S​p​a​c​e​b​a​r​!
		 */
		HEADING: string
		/**
		 * T​O​D​O
		 */
		TEXT: string
	}
	COMMON: {
		/**
		 * S​i​g​n​ ​I​n
		 */
		SIGN_IN: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		SIGN_UP: string
		/**
		 * G​e​t​ ​S​t​a​r​t​e​d
		 */
		GET_STARTED: string
		/**
		 * I​n​s​t​a​g​r​a​m
		 */
		INSTAGRAM: string
		/**
		 * T​w​i​t​t​e​r
		 */
		TWITTER: string
		/**
		 * G​i​t​H​u​b
		 */
		GITHUB: string
		/**
		 * G​o​t​ ​I​t
		 */
		GOT_IT: string
	}
	NAVBAR: {
		/**
		 * D​e​m​o
		 */
		DEMO_ALPHA_WARNING_BADGE: string
	}
	SECTIONS: {
		/**
		 * A​b​o​u​t
		 */
		ABOUT: string
		/**
		 * R​o​a​d​m​a​p
		 */
		ROADMAP: string
		/**
		 * I​n​s​t​a​n​c​e​s
		 */
		INSTANCES: string
		/**
		 * C​o​n​t​r​i​b​u​t​e
		 */
		CONTRIBUTE: string
		/**
		 * D​o​c​s
		 */
		DOCS: string
	}
	MAIN_PAGE: {
		PAGE_HEADER: {
			/**
			 * T​a​l​k​ ​n​i​c​e​!
			 */
			BIG_MARKETING_TEXT: string
			/**
			 * R​a​n​d​o​m​,​ ​s​m​a​l​l​ ​m​a​r​k​e​t​i​n​g​ ​t​e​x​t​ ​f​o​r​ ​t​e​s​t​ ​p​u​r​p​o​s​e​s​.
			 */
			SMALL_MARKETING_TEXT: string
			/**
			 * O​p​e​n​ ​D​e​m​o
			 */
			CTA_BUTTON_DEMO: string
			/**
			 * C​o​n​t​r​i​b​u​t​e
			 */
			CTA_BUTTON_CONTRIBUTE: string
			/**
			 * G​e​t​ ​S​t​a​r​t​e​d
			 */
			CTA_BUTTON_DOCS: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Spacebar
	 */
	PROJECT_NAME: () => LocalizedString
	/**
	 * It's time to ditch Skype, Teamspeak, and Discord.
	 */
	PROJECT_META_SLOGAN: () => LocalizedString
	META: {
		/**
		 * 2023 © Spacebar and Spacebar contributors
		 */
		COPYRIGHT_DISCLAIMER: () => LocalizedString
		/**
		 * Discord and the Discord logo are registered trademarks of Discord Inc. Spacebar is not affiliated with Discord Inc.
		 */
		DISCORD_COPYRIGHT_DISCLAIMER: () => LocalizedString
	}
	ONGOING_PROJECT_WARNING: {
		/**
		 * ⚠️ Hey! Spacebar is an ongoing project in early stages of development and it is not ready for production yet.
		 */
		CTA_HEADING: () => LocalizedString
		/**
		 * Read more
		 */
		CTA_READ_MORE: () => LocalizedString
		/**
		 * We're still developing Spacebar!
		 */
		HEADING: () => LocalizedString
		/**
		 * TODO
		 */
		TEXT: () => LocalizedString
	}
	COMMON: {
		/**
		 * Sign In
		 */
		SIGN_IN: () => LocalizedString
		/**
		 * Sign Up
		 */
		SIGN_UP: () => LocalizedString
		/**
		 * Get Started
		 */
		GET_STARTED: () => LocalizedString
		/**
		 * Instagram
		 */
		INSTAGRAM: () => LocalizedString
		/**
		 * Twitter
		 */
		TWITTER: () => LocalizedString
		/**
		 * GitHub
		 */
		GITHUB: () => LocalizedString
		/**
		 * Got It
		 */
		GOT_IT: () => LocalizedString
	}
	NAVBAR: {
		/**
		 * Demo
		 */
		DEMO_ALPHA_WARNING_BADGE: () => LocalizedString
	}
	SECTIONS: {
		/**
		 * About
		 */
		ABOUT: () => LocalizedString
		/**
		 * Roadmap
		 */
		ROADMAP: () => LocalizedString
		/**
		 * Instances
		 */
		INSTANCES: () => LocalizedString
		/**
		 * Contribute
		 */
		CONTRIBUTE: () => LocalizedString
		/**
		 * Docs
		 */
		DOCS: () => LocalizedString
	}
	MAIN_PAGE: {
		PAGE_HEADER: {
			/**
			 * Talk nice!
			 */
			BIG_MARKETING_TEXT: () => LocalizedString
			/**
			 * Random, small marketing text for test purposes.
			 */
			SMALL_MARKETING_TEXT: () => LocalizedString
			/**
			 * Open Demo
			 */
			CTA_BUTTON_DEMO: () => LocalizedString
			/**
			 * Contribute
			 */
			CTA_BUTTON_CONTRIBUTE: () => LocalizedString
			/**
			 * Get Started
			 */
			CTA_BUTTON_DOCS: () => LocalizedString
		}
	}
}

export type Formatters = {}
