// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * F​o​s​s​c​o​r​d
	 */
	PROJECT_NAME: string
	COMMON: {
		/**
		 * S​i​g​n​ ​I​n
		 */
		SIGN_IN: string
		/**
		 * S​i​g​n​ ​U​p
		 */
		SIGN_UP: string
		/**
		 * G​e​t​ ​S​t​a​r​t​e​d
		 */
		GET_STARTED: string
		/**
		 * G​i​t​H​u​b
		 */
		GITHUB: string
	}
	NAVBAR: {
		/**
		 * D​e​m​o​/​A​l​p​h​a
		 */
		DEMO_ALPHA_WARNING_BADGE: string
	}
	SECTIONS: {
		/**
		 * A​b​o​u​t
		 */
		ABOUT: string
		/**
		 * R​o​a​d​m​a​p
		 */
		ROADMAP: string
		/**
		 * I​n​s​t​a​n​c​e​s
		 */
		INSTANCES: string
		/**
		 * C​o​n​t​r​i​b​u​t​e
		 */
		CONTRIBUTE: string
		/**
		 * D​o​c​s
		 */
		DOCS: string
	}
	MAIN_PAGE: {
		PAGE_HEADER: {
			/**
			 * T​a​l​k​ ​n​i​c​e​!
			 */
			BIG_MARKETING_TEXT: string
			/**
			 * R​a​n​d​o​m​,​ ​s​m​a​l​l​ ​m​a​r​k​e​t​i​n​g​ ​t​e​x​t​ ​f​o​r​ ​t​e​s​t​ ​p​u​r​p​o​s​e​s​.
			 */
			SMALL_MARKETING_TEXT: string
			/**
			 * O​p​e​n​ ​D​e​m​o
			 */
			CTA_BUTTON_DEMO: string
			/**
			 * C​o​n​t​r​i​b​u​t​e
			 */
			CTA_BUTTON_CONTRIBUTE: string
			/**
			 * G​e​t​ ​S​t​a​r​t​e​d
			 */
			CTA_BUTTON_DOCS: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Fosscord
	 */
	PROJECT_NAME: () => LocalizedString
	COMMON: {
		/**
		 * Sign In
		 */
		SIGN_IN: () => LocalizedString
		/**
		 * Sign Up
		 */
		SIGN_UP: () => LocalizedString
		/**
		 * Get Started
		 */
		GET_STARTED: () => LocalizedString
		/**
		 * GitHub
		 */
		GITHUB: () => LocalizedString
	}
	NAVBAR: {
		/**
		 * Demo/Alpha
		 */
		DEMO_ALPHA_WARNING_BADGE: () => LocalizedString
	}
	SECTIONS: {
		/**
		 * About
		 */
		ABOUT: () => LocalizedString
		/**
		 * Roadmap
		 */
		ROADMAP: () => LocalizedString
		/**
		 * Instances
		 */
		INSTANCES: () => LocalizedString
		/**
		 * Contribute
		 */
		CONTRIBUTE: () => LocalizedString
		/**
		 * Docs
		 */
		DOCS: () => LocalizedString
	}
	MAIN_PAGE: {
		PAGE_HEADER: {
			/**
			 * Talk nice!
			 */
			BIG_MARKETING_TEXT: () => LocalizedString
			/**
			 * Random, small marketing text for test purposes.
			 */
			SMALL_MARKETING_TEXT: () => LocalizedString
			/**
			 * Open Demo
			 */
			CTA_BUTTON_DEMO: () => LocalizedString
			/**
			 * Contribute
			 */
			CTA_BUTTON_CONTRIBUTE: () => LocalizedString
			/**
			 * Get Started
			 */
			CTA_BUTTON_DOCS: () => LocalizedString
		}
	}
}

export type Formatters = {}
